---
# tasks file for roles/growi
- name: Clone growi repository
  git:
    repo: 'https://github.com/weseek/growi-docker-compose.git'
    dest: growi
    clone: yes
    update: yes
    version: '{{ version }}'

- name: Enable access from other hosts
  replace:
    path: docker-compose.yml
    regexp: '127.0.0.1:3000:3000'
    replace: '3000:3000'
  notify:
    - docker compose up

- name: Modify environment of my domain
  replace:
    path: examples/https-portal/docker-compose.override.yml
    regexp: 'example.com'
    replace: '{{ mydomain }}'
  notify:
    - Copy override yml for https-portal
    - docker compose up